name: Bug Report
description: Report unexpected behaviour or crashes
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "**Before submitting your issue, please confirm that it has not already been reported!**"
  - type: textarea
    id: error
    attributes:
      label: Issue
      description: Please describe the issue here
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Logs
      description: Please paste the contents of your server log here. Please ensure there is no sensitive data in this log
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Terms
      options:
        - label: I have checked and confirmed that this issue has not already been reported before
          required: true
